### ISSUE TITLE
anvi-self-test issue

### ISSUE THREAD

**Issue by amaralzettler** [meren/anvio#237] opened 2015-12-03 16:42 UTC
I just tried to install the latest version of Anvi'o using the Mac OS installer and when I try to run the self test I get the following error:

[Amaral-Zettler-MacBook-Pro:~] amaral2% source /Applications/Anvio.app/Contents/Resources/Scripts/activate.sh
baseDir=/Applications/Anvio.app/Contents/Resources/base: Command not found.
baseDir: Undefined variable.
[Amaral-Zettler-MacBook-Pro:~] amaral2% anvi-self-test
anvi-self-test: Command not found.

Please advise,

Thanks,

Linda

**Comment by ozcanesen** [comment] 2015-12-03 17:05
Hello Linda,
What happens when you launch Anvio from Launchpad? And what is your OS X version?

And also can you post the output of 
`cat /Applications/Anvio.app/Contents/Resources/Scripts/activate.sh`

Thanks,

**Comment by amaralzettler** [comment] 2015-12-03 17:50
Hi Özcan,

I¹m running OS X Yosemite version 10.10.5.  I get the same message when I
launch anvi¹o from the Launchpad:

Last login: Thu Dec  3 12:38:48 on console
[Amaral-Zettler-MacBook-Pro:~] amaral2% source
/Applications/Anvio.app/Contents/Resources/Scripts/activate.sh
baseDir=/Applications/Anvio.app/Contents/Resources/base: Command not found.
baseDir: Undefined variable.
[Amaral-Zettler-MacBook-Pro:~] amaral2%

This is what I get when I run
cat /Applications/Anvio.app/Contents/Resources/Scripts/activate.sh

[Amaral-Zettler-MacBook-Pro:~] amaral2% cat
/Applications/Anvio.app/Contents/Resources/Scripts/activate.sh
baseDir="/Applications/Anvio.app/Contents/Resources/base"

export PYTHONHOME=$baseDir
export PYTHONPATH=$baseDir/:$baseDir/anvio/
export PATH=$baseDir/bin:$PATH
if [ "$(echo $BASH)" = '/bin/bash' ]; then
export PS1="\[\e[0m\e[47m\e[1;30m\] :: anvi'o :: \[\e[0m\e[0m
\[\e[1;34m\]\]\w\[\e[m\] \[\e[1;32m\]$\[\e[m\] \[\e[0m\]"
else
export PS1=" :: anvi'o :: $ "
fi

Clear

Please advise ­ many thanks,

Linda
~~~~~~~~~~~~~~~~~~~~~
Linda Amaral Zettler, Ph.D.
Associate Scientist/Associate Professor
Josephine Bay Paul Center/Brown University Department of Earth,
Environmental and Planetary Sciences
Marine Biological Laboratory
7 MBL Street
Woods Hole, MA 02543
http: //amarallab.mbl.edu
From:  Özcan Esen <notifications@github.com>
Reply-To:  meren/anvio
<reply+00c4d5f18ffb6a0edc2217be875d5ebd08c967091e9c8e9892cf000000011278385c9
2a169ce072a5efe@reply.github.com>
Date:  Thursday, December 3, 2015 at 12:05 PM
To:  meren/anvio <anvio@noreply.github.com>
Cc:  Linda Amaral Zettler <amaral@mbl.edu>
Subject:  Re: [anvio] anvi-self-test issue (#237)


Hello Linda,
What happens when you launch Anvio from Launchpad? And what is your OS X
version?

And also can you post the output of
cat /Applications/Anvio.app/Contents/Resources/Scripts/activate.sh

Thanks,


Reply to this email directly or view it on GitHub
<https://github.com/meren/anvio/issues/237#issuecomment-161717543> .

**Comment by amaralzettler** [comment] 2015-12-10 18:17
Hi Özcan,

I¹m hoping to do more anvio-ing today but I¹m not sure how to proceed with
my issues.  Do you happen to know if I can run 1.1.0 on our servers at MBL
to avoid running into problems with Anvio-interactive on my desktop?
Alternatively, I saw the blog entry about running Anvio interactive through
the ssh tunnel ­ is this my best option?

Please advise,

Thanks,

Linda
~~~~~~~~~~~~~~~~~~~~~
Linda Amaral Zettler, Ph.D.
Associate Scientist/Associate Professor
Josephine Bay Paul Center/Brown University Department of Earth,
Environmental and Planetary Sciences
Marine Biological Laboratory
7 MBL Street
Woods Hole, MA 02543
http: //amarallab.mbl.edu

From:  Özcan Esen <notifications@github.com>
Reply-To:  meren/anvio
<reply+00c4d5f18ffb6a0edc2217be875d5ebd08c967091e9c8e9892cf000000011278385c9
2a169ce072a5efe@reply.github.com>
Date:  Thursday, December 3, 2015 at 12:05 PM
To:  meren/anvio <anvio@noreply.github.com>
Cc:  Linda Amaral Zettler <amaral@mbl.edu>
Subject:  Re: [anvio] anvi-self-test issue (#237)


Hello Linda,
What happens when you launch Anvio from Launchpad? And what is your OS X
version?

And also can you post the output of
cat /Applications/Anvio.app/Contents/Resources/Scripts/activate.sh

Thanks,


Reply to this email directly or view it on GitHub
<https://github.com/meren/anvio/issues/237#issuecomment-161717543> .

**Comment by ozcanesen** [comment] 2015-12-10 20:29
Hi Linda,

Sorry for the late answer, but i could not able to produce the error you had on 3 different versions of OS X, because the script that causes the error is very simple and i -think- problem comes from somewhere else but it is very hard to understand remotely, you should not get same error on clean installation of Anvi'o on different computer. Blaming the computer and closing the issue are such cliches for the issue reports like this so i do not want to do that. Maybe we should keep this issue open until some other user have exact same problem then we can investigate more deeply with additional information.

About installation on server, you can follow Docker instructions http://merenlab.org/2015/08/22/docker-image-for-anvio/,
Also it is a good alternative to OS X App of Anvi'o, you can use it on your laptop. Since your current installation does not work you should also give it a chance on your laptop.

All the best,
Ozcan

**Comment by amaralzettler** [comment] 2015-12-10 22:05
Hi Ozcan,

I¹m running anvio on minnie now ­ I was able to run the MyRAST portion on my
laptop and so I¹ll need to see if I can get the anvi-interactive running
somewhere else when the processing is complete.

So, I¹m a bit confused by your comment about the Docker  is this required
for SSH tunneling use of anvi-interactive?

I have anvio 1.1.0 installed on my laptop but I used the github method of
installation  removing the last version of anvio.  I was hoping to not have
to remove the earlier version of the program and just have both available
since I have some older profiles I ran.  Maybe this is a bad idea.  I was
thinking to hold out until anvio 2.0 before making the next installation of
anvio.  Joe is running 2 versions but he used the Docker to install the
latest update (and also has 1.1.0 running).  I was hoping to do the same but
not so lucky.

Any insights, clarifications you have would be appreciated.

Thanks,

Linda
~~~~~~~~~~~~~~~~~~~~~
Linda Amaral Zettler, Ph.D.
Associate Scientist/Associate Professor
Josephine Bay Paul Center/Brown University Department of Earth,
Environmental and Planetary Sciences
Marine Biological Laboratory
7 MBL Street
Woods Hole, MA 02543
http: //amarallab.mbl.edu

From:  Özcan Esen <notifications@github.com>
Reply-To:  meren/anvio
<reply+00c4d5f19da7e9038ab76aa4e592637d60a5807a62ccafba92cf000000011281a2c79
2a169ce072a5efe@reply.github.com>
Date:  Thursday, December 10, 2015 at 3:29 PM
To:  meren/anvio <anvio@noreply.github.com>
Cc:  Linda Amaral Zettler <amaral@mbl.edu>
Subject:  Re: [anvio] anvi-self-test issue (#237)


Hi Linda,

Sorry for the late answer, but i could not able to produce the error you had
on 3 different versions of OS X, because the script that causes the error is
very simple and i -think- problem comes from somewhere else but it is very
hard to understand remotely, you should not get same error on clean
installation of Anvi'o on different computer. Blaming the computer and
closing the issue are such cliches for the issue reports like this so i do
not want to do that. Maybe we should keep this issue open until some other
user have exact same problem then we can investigate more deeply with
additional information.

About installation on server, you can follow Docker instructions
http://merenlab.org/2015/08/22/docker-image-for-anvio/,
Also it is a good alternative to OS X App of Anvi'o, you can use it on your
laptop. Since your current installation does not work you should also give
it a chance on your laptop.

All the best,
Ozcan


Reply to this email directly or view it on GitHub
<https://github.com/meren/anvio/issues/237#issuecomment-163740838> .

**Comment by amaralzettler** [comment] 2015-12-11 19:34
Hi Ozcan,

It does appear to be something with my computer because I just installed it
on Beth¹s old computer for now and there were no problems with the install.
Just for the fun of it, I tried uninstalling and reinstalling but it still
doesn¹t work.  One difference is that on Beth¹s machine, a bash shell opens
and on mine is a tcsh.  However on Beth¹s machine I see a :: anvi¹o :: ~$
prompt wherein on mine, this window never comes up and I get the message:

Last login: Fri Dec 11 14:27:51 on ttys001
source /Applications/Anvio.app/Contents/Resources/Scripts/activate.sh
[Amaral-Zettler-MacBook-Pro:~] amaral2% source
/Applications/Anvio.app/Contents/Resources/Scripts/activate.sh
baseDir=/Applications/Anvio.app/Contents/Resources/base: Command not found.
baseDir: Undefined variable.
[Amaral-Zettler-MacBook-Pro:~] amaral2%

Beth is running Mac OS 10.8.

Let me know if this helps with troubleshooting at all.

Thanks,

Linda
~~~~~~~~~~~~~~~~~~~~~
Linda Amaral Zettler, Ph.D.
Associate Scientist/Associate Professor
Josephine Bay Paul Center/Brown University Department of Earth,
Environmental and Planetary Sciences
Marine Biological Laboratory
7 MBL Street
Woods Hole, MA 02543
http: //amarallab.mbl.edu
From:  Özcan Esen <notifications@github.com>
Reply-To:  meren/anvio
<reply+00c4d5f19da7e9038ab76aa4e592637d60a5807a62ccafba92cf000000011281a2c79
2a169ce072a5efe@reply.github.com>
Date:  Thursday, December 10, 2015 at 3:29 PM
To:  meren/anvio <anvio@noreply.github.com>
Cc:  Linda Amaral Zettler <amaral@mbl.edu>
Subject:  Re: [anvio] anvi-self-test issue (#237)


Hi Linda,

Sorry for the late answer, but i could not able to produce the error you had
on 3 different versions of OS X, because the script that causes the error is
very simple and i -think- problem comes from somewhere else but it is very
hard to understand remotely, you should not get same error on clean
installation of Anvi'o on different computer. Blaming the computer and
closing the issue are such cliches for the issue reports like this so i do
not want to do that. Maybe we should keep this issue open until some other
user have exact same problem then we can investigate more deeply with
additional information.

About installation on server, you can follow Docker instructions
http://merenlab.org/2015/08/22/docker-image-for-anvio/,
Also it is a good alternative to OS X App of Anvi'o, you can use it on your
laptop. Since your current installation does not work you should also give
it a chance on your laptop.

All the best,
Ozcan


Reply to this email directly or view it on GitHub
<https://github.com/meren/anvio/issues/237#issuecomment-163740838> .

**Comment by ozcanesen** [comment] 2015-12-11 21:06
Hi Linda,

Yes this is the reason, i reproduced the error with tcsh. But we are -at least i am- not going to fix that because i do not know the tcsh's scripting language also bash, sh and zsh are the de-facto standards for the unix (osx, gnu/linux, etc..) universe, and they are compatible with each other. You should change your shell which is not compatible with bash only if you can convert bash scripts to your shell's scripting your language otherwise it can cause problems like this. 

You can revert your shell back to bash using command below to use Anvi'o properly (if you do not have a good reason or dependent tools/applications that use tcsh i highly recommend this)
```chsh -s /bin/bash```
Also you can go back to tcsh anytime with
```chsh -s /bin/tcsh```

Best,
Özcan

**Closed by ozcanesen** 2015-12-11 21:06 UTC

**Comment by amaralzettler** [comment] 2015-12-12 15:00
Awesome ­ that solved the problem!!  Thanks so much for the fix :)).

L

From:  Özcan Esen <notifications@github.com>
Reply-To:  meren/anvio
<reply+00c4d5f11d898d15c7dd85a36de325bae32379b706eb9bd492cf000000011282fccc9
2a169ce072a5efe@reply.github.com>
Date:  Friday, December 11, 2015 at 4:06 PM
To:  meren/anvio <anvio@noreply.github.com>
Cc:  Linda Amaral Zettler <amaral@mbl.edu>
Subject:  Re: [anvio] anvi-self-test issue (#237)


Hi Linda,

Yes this is the reason, i reproduced the error with tcsh. But we are -at
least i am- not going to fix that because i do not know the tcsh's scripting
language also bash, sh and zsh are the de-facto standards for the unix (osx,
gnu/linux, etc..) universe, and they are compatible with each other. You
should change your shell which is not compatible with bash only if you can
convert bash scripts to your shell's scripting your language otherwise it
can cause problems like this.

You can revert your shell back to bash using command below to use Anvi'o
properly (if you do not have a good reason or dependent tools/applications
that use tcsh i highly recommend this)
chsh -s /bin/bash
Also you can go back to tcsh anytime with
chsh -s /bin/tcsh

Best,
Özcan


Reply to this email directly or view it on GitHub
<https://github.com/meren/anvio/issues/237#issuecomment-164047463> .

**Comment by alexximalayaunlv** [comment] 2019-06-14 16:52
Hi, I encountered similar problem with bash. The anvio 5.5 was installed using conda using the code below:

conda create -y  python=3.6 -p /storage/hedlundlab/dengxun/software/conda/anvio

The installation information is as follows: 
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use:
# > source activate /storage/hedlundlab/dengxun/software/conda/anvio
#
# To deactivate an active environment, use:
# > source deactivate

But I tried source activate /storage/hedlundlab/dengxun/software/conda/anvio and run "anvi-self-test --suite mini", it showed "bash: anvi-self-test: command not found..."

Any ideas? Thank you!
