### ISSUE TITLE
anvi'server taking a long time

### ISSUE THREAD

**Issue by ShaiberAlon** [meren/anvio#346] opened 2016-04-08 21:03 UTC
Hi,

On anvi'server, this takes a very long time, and if you click Draw before it finishes this process then it doesn't work properly (and then you have to refresh and draw after it finishes). 

![image](https://cloud.githubusercontent.com/assets/17661044/14396982/65b95d3a-fda0-11e5-833d-26969e63dfc4.png)

**Comment by meren** [comment] 2016-04-08 21:10
Hi Tobi,

Just a note. I guess this is the lookup from Gravatar, but I am not sure. It takes a very long time (i.e., a minute), and when I clicked the Draw button while this takes place, for some reason things go south.

How can we reduce that minute? :(

I hope all is well!


Best wishes,

**Comment by meren** [comment] 2016-04-08 21:27
This happens with publicly shared project. A related issue is this: when a project is shared "privately", that section is completely missing, so the visiting user cannot download the data:

![image](https://cloud.githubusercontent.com/assets/197307/14398038/ada64008-fda6-11e5-887f-266c2da5b1da.png)


Best,

**Comment by meren** [comment] 2016-04-08 21:54
An update: the presence or absence of that layer with username and avatar changes depending on whether the person accessing the resource is logged in or not.

**Comment by paczian** [comment] 2016-04-13 09:39
This is at least partially addressed in #351 
The problem is that the files of the project are transferred so they are available for download in the info window. This is now an additional call to prevent the UI from locking. I don't know how large the files get (I thought they were supposed to be <5MB), but if they get larger the download would need to be done differently.

**Comment by paczian** [comment] 2016-04-13 11:09
The layer should always be present, not logged in:

![screen shot 2016-04-13 at 06 05 15](https://cloud.githubusercontent.com/assets/1032895/14491355/e513b9b8-013d-11e6-905a-bc6e41a66738.png)

logged in:

![screen shot 2016-04-13 at 06 07 22](https://cloud.githubusercontent.com/assets/1032895/14491375/060a0ac8-013e-11e6-827d-1f84ea435ae1.png)

**Closed** 2016-06-07 14:39 UTC
Labels: enhancement, server
